const example = [
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
  {date: null, availability: 0},
];

export default example;

// var objFormatter = function(day) {

// }


// var generateAllDates = function() {
//   var output = [];

//   for (var i = 0; i < 365; i++) {

//   }
// }